### ISSUE TITLE
Implement Log Rotation for Efficient Log Management

### ISSUE THREAD

**Issue by Bahugunajii** [avantifellows/db-service#143]
**Describe the task**
- Currently, all logs are sent to the `info.log` file, leading to its continuous growth and potential issues with log management. To address this, we need to implement log rotation for a more organized and sustainable logging system.

**Expected behaviour**
- We need to implement log rotation which involves periodically archiving or truncating the existing log file to prevent it from becoming excessively large. This ensures better log management and facilitates easy analysis of log data.

**Comment by suryabulusu** [comment]
also take a look at logger and why it is not working with elixir 1.16 .. why should we fixate on elixir 1.14

**Comment by Bahugunajii** [comment]
It's already working no?

**Comment by Bahugunajii** [comment]
![image](https://github.com/avantifellows/db-service/assets/107760942/4b69a178-9da6-4b38-8b06-042adeee53ab)
