### ISSUE TITLE
Fetch all enrollment-record details

### ISSUE THREAD

**Issue by Bahugunajii** [avantifellows/db-service#74]
**Describe the task**
Currently, while fetching all the enrollement records in the database, two fields present in the database are missing in response which are: `academic_year` and `board_medium`

**Expected behavior**
We need to fetch these two fields lying inside the enrollment record while retrieving the  enrollment records somewhat like this:

![image](https://user-images.githubusercontent.com/107760942/227491442-5d1f026c-ee47-45fe-bba9-eefb460f8e2c.png)

**Comment by belwalshubham** [comment]
But I already get these two fields when I run the API endpoint in postman. can you check it once ? and correct me if I'm wrong. 

![image](https://user-images.githubusercontent.com/61574835/227500194-4808bcf1-5185-4fd0-b72f-1221f6543402.png)

**Comment by Bahugunajii** [comment]
Hey, I think you are not up-to-date as per the main branch. Try running `mix setup` to run all the jobs again

**Comment by belwalshubham** [comment]
Okay thanks!
